//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace RhythmosEngine
{
	/// <summary>
	/// Representation of a Note Layout.
	/// </summary>
	public class NoteLayout {
	
		[SerializeField]
		string m_name;
		
		[SerializeField]
		AudioClip m_clip;
		
		[SerializeField]
		Color m_color;
		
		/// <summary>
		/// Gets or sets the name.
		/// </summary>
		/// <value>The name.</value>
		public string Name {
			get {return m_name;}
			set {m_name = value;}
		}
		
		/// <summary>
		/// Gets or sets the Audio Clip.
		/// </summary>
		/// <value>The clip.</value>
		public AudioClip Clip {
			get {return m_clip;}
			set {m_clip = value;}
		}
		
		/// <summary>
		/// Gets or sets the Color.
		/// </summary>
		/// <value>The color.</value>
		public Color Color {
			get {return m_color;}
			set {m_color = value;}
		}
	
	/// <summary>
	/// Initializes a new instance of the <see cref="RhythmosEngine.NoteLayout"/> class.
	/// </summary>
	public NoteLayout() {
		
			this.m_name = "";
			this.m_clip = null;
			this.m_color = new Color(Random.Range(0.3f,0.95f),Random.Range(0.3f,0.95f),Random.Range(0.3f,0.95f));

	}

	/// <summary>
	/// Initializes a new instance of the <see cref="RhythmosEngine.NoteLayout"/> class.
	/// Audio clip will be null and color is randomized.
	/// </summary>
	/// <param name="name">Note layout name</param>
	public NoteLayout(string name) {
		
			this.m_name = name;
			this.m_clip = null;
			this.m_color = new Color(Random.Range(0.3f,0.95f),Random.Range(0.3f,0.95f),Random.Range(0.3f,0.95f));
		
		
	}

	/// <summary>
	/// Initializes a new instance of the <see cref="RhythmosEngine.NoteLayout"/> class.
	/// Color is randomized.
	/// </summary>
	/// <param name="name">Note layout Name.</param>
	/// <param name="clip">Note layout AudioClip.</param>
	public NoteLayout(string name, AudioClip clip) {
			
			this.m_name = name;
			this.m_clip = clip;
			this.m_color = new Color(Random.Range(0.3f,0.95f),Random.Range(0.3f,0.95f),Random.Range(0.3f,0.95f));
			
			
	}

	/// <summary>
	/// Initializes a new instance of the <see cref="RhythmosEngine.NoteLayout"/> class.
	/// </summary>
	/// <param name="name">Note layout Name.</param>
	/// <param name="clip">Note layout Clip.</param>
	/// <param name="color">Note layout Color.</param>
	public NoteLayout(string name, AudioClip clip, Color color) {
			
			this.m_name = name;
			this.m_clip = clip;
			this.m_color = color;

	}
	/// <summary>
	/// Initializes a new instance of the <see cref="RhythmosEngine.NoteLayout"/> class based in another NoteLayout.
	/// </summary>
	/// <param name="noteLayout">Note layout.</param>
	public NoteLayout(NoteLayout noteLayout) {
			this.m_name = noteLayout.Name;
			this.m_color = noteLayout.Color;
			this.m_clip = noteLayout.Clip;
	}


	


	}
}

