//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

namespace RhythmosEngine
{
    /// <summary>
    /// Rhythm Class provides a data storage for rhythm: rhythm name, note list, bpm.
    /// </summary>
    [Serializable]
    public class Rhythm
    {
        [SerializeField]
        private List<Note> m_noteList;

        /// <summary>
        /// Rhythm name.
        /// </summary>
        public string Name = "none";

        /// <summary>
        /// Beats per minute.
        /// </summary>
        public float BPM = 80;

        /// <summary>
        /// Gets the note count.
        /// </summary>
        /// <value>The note count.</value>
        [Obsolete("Please use 'Count' method instead. Just to simplify things.", true)]
        public int NoteCount
        {
            get
            {
                return m_noteList.Count;
            }
        }

        /// <summary>
        /// Gets the note count.
        /// </summary>
        public int Count
        {
            get
            {
                return m_noteList.Count;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RhythmosEngine.Rhythm"/> class.
        /// </summary>
        public Rhythm()
        {
            Name = "none";
            BPM = 80;
            m_noteList = new List<Note>();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RhythmosEngine.Rhythm"/> class.
        /// </summary>
        /// <param name="name">Name.</param>
        /// <param name="bpm">BPM.</param>
        public Rhythm(string name, float bpm)
        {
            Name = name;
            BPM = bpm;
            m_noteList = new List<Note>();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RhythmosEngine.Rhythm"/> class cloning another Rhythm instance.
        /// </summary>
        /// <param name="rhythm">Rhythm.</param>
        public Rhythm(Rhythm rhythm)
        {
            Name = rhythm.Name;
            BPM = rhythm.BPM;
            m_noteList = new List<Note>();

            foreach (Note nt in rhythm.NoteList())
            {
                m_noteList.Add(new Note(nt));
            }
        }

        /// <summary>
        /// Appends a note to Rhythm.
        /// </summary>
        /// <param name="note">Note.</param>
        public void AppendNote(Note note)
        {
            m_noteList.Add(note);
        }

        /// <summary>
        /// Appends a note.
        /// </summary>
        /// <param name="layoutIndex">Layout index.</param>
        /// <param name="note_duration">Note_duration.</param>
        /// <param name="is_pause">If set to <c>true</c> is_pause.</param>
        public void AppendNote(int layoutIndex, float noteDuration, bool isRest)
        {
            Note newNote = new Note();
            newNote.isRest = isRest;
            newNote.duration = noteDuration;
            newNote.layoutIndex = layoutIndex;
            m_noteList.Add(newNote);
        }

        /// <summary>
        /// Inserts a note at index.
        /// </summary>
        /// <param name="index">Index.</param>
        /// <param name="note">Note.</param>
        public void InsertNoteAt(int index, Note note)
        {
            m_noteList.Insert(index, note);
        }

        /// <summary>
        /// Removes a note at index.
        /// </summary>
        /// <param name="index">Index.</param>
        public void RemoveNote(int index)
        {
            m_noteList.RemoveAt(index);
        }

        /// <summary>
        /// Replaces a note at index.
        /// </summary>
        /// <param name="index">Index.</param>
        /// <param name="note">Note.</param>
        public void ReplaceNote(int index, Note note)
        {
            m_noteList.RemoveAt(index);
            m_noteList.Insert(index, note);
        }

        /// <summary>
        /// Swaps a note in the index to swapIndex.
        /// </summary>
        /// <param name="index">Index.</param>
        /// <param name="swapIndex">Swap index.</param>
        public void SwapNote(int index, int swapIndex)
        {
            Note note = new Note(m_noteList[index]);
            Note noteSwap = new Note(m_noteList[swapIndex]);

            m_noteList.RemoveAt(index);
            m_noteList.Insert(index, noteSwap);

            m_noteList.RemoveAt(swapIndex);
            m_noteList.Insert(swapIndex, note);

        }

        /// <summary>
        /// Clear the note list.
        /// </summary>
        public void Clear()
        {
            m_noteList.Clear();
        }


        /// <summary>
        /// Duration of Rhythm by BPM.
        /// </summary>
        public float Duration()
        {
            float totalTime = 0f;
            if (BPM > 0)
            {
                foreach (Note nt in m_noteList)
                {
                    totalTime += nt.duration;
                }
                totalTime *= (60f / BPM);
            }

            return totalTime;
        }

        /// <summary>
        /// Notes the list.
        /// </summary>
        /// <returns>Note list.</returns>
        public List<Note> NoteList()
        {
            return m_noteList;
        }

        /// <summary>
        /// Gets the note at index.
        /// </summary>
        /// <returns>The <see cref="RhythmosEngine.Note"/>.</returns>
        /// <param name="index">Index.</param>
        public Note GetNoteAt(int index)
        {
            return m_noteList[index];
        }

    };
}

