//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace RhythmosEngine
{
	public static class RhythmosUtility
	{
		/// <summary>
		/// Checks if the source Rhythm A matches with a destination Rhythm B according with notes layout.
		/// The note duration is ignored.
		/// </summary>
		/// <returns><c>true</c>, if was matched, <c>false</c> otherwise.</returns>
		/// <param name="rhythmA">Rhythm A</param>
		/// <param name="rhythmB">Rhythm B</param>
		/// <param name="elementsToCompare">Elements to compare.</param>
		static public bool CheckRhythmsMatch(Rhythm rhythmA, Rhythm rhythmB) { 
			
			bool match = false;	
			if (rhythmA != null) {
				if (rhythmB != null) {
			
					if (rhythmA.NoteList().Count == rhythmB.NoteList().Count) { // o ritmo tocado tem o mesmo numero de notas
						for (int i = 0; i < rhythmB.NoteList().Count; i++) {
						
							bool isPause = false;
							
							isPause = rhythmA.NoteList()[i].isRest;
							
							if (isPause) {
							
								if (rhythmA.NoteList()[i].isRest == rhythmB.NoteList()[i].isRest) {
									match = true;
								} else {
									match = false;
									break;
								}
							
							} else {
		
								if (rhythmA.NoteList()[i].layoutIndex == rhythmB.NoteList()[i].layoutIndex) {
									match = true;
								} else {
									match = false;
									break;
								}
							}
		
						}
					}
				} else {
					Debug.LogError("RhythmosEngine: RhythmosUtility: The rhythm B is null.\nImpossible to check rhythms match.");
					return false;
				}
				
			} else {
				Debug.LogError("RhythmosEngine: RhythmosUtility: The rhythm A is null.\nImpossible to check rhythms match.");
				return false;
			}
			
			return match;
			
		}

		/// <summary>
		/// Check if the Source rhythm matches with some of the rhythms from a RhythmosDatabase.
		/// </summary>
		/// <returns> the matched <c>Rhythm</c> from the database, <c>null</c> otherwise.</returns>
		/// <param name="sourceRhythm">Rhythm to check.</param>
		static public Rhythm CheckDatabaseRhythmMatch(RhythmosDatabase rhythmDatabase, Rhythm sourceRhythm) { 

			if (rhythmDatabase != null) {
				if (sourceRhythm != null) {

					// o map de ritmos tem alguem?
					if (rhythmDatabase.RhythmsCount > 0) {
						
						// loop em torno do map de ritmos
						foreach (Rhythm rtmIt in rhythmDatabase.GetRhythmList()) {
							
							bool matched = false;
							
							// verifica se o ritmo FONTE tem a mesma quantidade de notas que o ritmo DESTINO
							if (sourceRhythm.NoteList().Count == rtmIt.NoteList().Count) {
								
								// verifica se o ritmo FONTE tem a mesmas notas do que o DESTINO
								matched = CheckRhythmsMatch(sourceRhythm,rtmIt);
								// encontrou um ritmo!
								if (matched) {
									return rtmIt;
								}						
							} else { // nao tem mesma quantidade de notas
								continue;
							}	
						}
					}
				} else {
					Debug.LogError("RhythmosEngine: RhythmosUtility: The source rhythm is null.\nImpossible to check a match from database.");
					return null;
				}
			
			} else {
			
				Debug.LogError("RhythmosEngine: RhythmosUtility: The RhythmosDatabase is null.\nImpossible to check a match from database.");
				return null;
			}
			
			return null;
			
		}

		/// <summary>
		/// Checks the precision of a source rhythm by a "compare" rhythm.
		/// Failure rate is a percentage from 0.0 to 1.0 for precision value.
		/// </summary>
		/// <returns>The precision between 0.0f ... 1.0f of the rhythm matches. If -1, the compare was unsuccessful.</returns>
		/// <param name="rhythmA">Rhythm source.</param>
		/// <param name="rhythmB">Rhythm compare.</param>
		/// <param name="failureRate">Failure Rate.</param>
		static public float CheckRhythmsPrecision(Rhythm rhythmSource, Rhythm rhythmCompare, float failureRate) {
			
			float result = 0;
			if (rhythmSource != null) {
				if (rhythmCompare != null) {
			
						float bpsec = 60f/rhythmCompare.BPM;
						float rightness = 0;
						float timeRtm = 0;
						float timeUsr = 0;
						
						for (int i = 0; i < rhythmCompare.NoteList().Count; i++) {
			
							// pega a duracao da nota pelo BPM
							float noteByBPM = bpsec * rhythmCompare.NoteList()[i].duration;
			
							// ponderacao desta nota
							float pdrc = noteByBPM*failureRate;
							
							if (i >= rhythmCompare.NoteList().Count-1) {
								
								noteByBPM = bpsec*rhythmCompare.NoteList()[i-1].duration;
								pdrc = noteByBPM*failureRate;
								
								if (timeUsr > timeRtm-pdrc && timeUsr < timeRtm+pdrc) {
									float por = rhythmSource.NoteList()[i-1].duration/noteByBPM;//Mathf.Lerp(0.1f,1f,rhythmSource.NoteList()[i-1].m_duration/noteByBPM);
									rightness += por;
								}	
							} else {
								timeRtm += noteByBPM;
								timeUsr += (bpsec*rhythmCompare.NoteList()[i].duration);
								// se esta dentro da ponderacao
								if (rhythmSource.NoteList()[i].duration > noteByBPM-pdrc && rhythmSource.NoteList()[i].duration < noteByBPM+pdrc) {
									float por = rhythmSource.NoteList()[i].duration/noteByBPM;//Mathf.Lerp(0.1f,1f,rhythmSource.NoteList()[i].m_duration/noteByBPM);
									rightness += por;
								}
							}
						
						}

					result = rightness;
					result = result/(float)rhythmCompare.NoteList().Count;
					if (result > 1f)
					{
						result = 1f;
					}
					else if (result < 0f)
					{
						result = 0f;
					}
						
			
				} else {
					Debug.LogError("RhythmosEngine: RhythmosUtility: The Compare Rhythm is null.\nImpossible to compare.");
					return -1;
				}
			
			} else {
				Debug.LogError("RhythmosEngine: RhythmosUtility: The Source Rhythm is null.\nImpossible to compare.");
				return -1;
			}
			
			return result;
			
		}
		
	}

}


