//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace RhythmosEditor
{
	public class ColorUtility {
		
		public static Color ParseColor(string col) {
			//Takes strings formatted with numbers and no spaces before or after the commas:
			// "1.0,1.0,.35,1.0"
			
			Color output = new Color(0,0,0,0);
			
			if (col.StartsWith("RGBA(")) {
				
				col = col.Remove(0,5);
				col = col.Remove(col.Length-1,1);
				
			} 
			
			//Debug.Log (col);
			//col = col.Replace(" ","");
			string[] strs = col.Split(","[0]);
			
			for (int i = 0; i < 4; i++) {
				//Debug.Log (strs[i]);
				output[i] = System.Single.Parse(strs[i]);
			}
			
			
			
			return output;
		}
	}
}

