//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace RhythmosEditor
{
	internal struct Note {
	
		[SerializeField]
		public bool isRest;
		
		[SerializeField]
		public float duration;
		
		[SerializeField]
		public int layoutIndex;
		
		/// <summary>
		/// Initializes a new instance of the <see cref="RhythmosEngine.Note"/> struct.
		/// </summary>
		/// <param name="duration">Note Duration.</param>
		/// <param name="isRest">If set to <c>true</c> is rest.</param>
		/// <param name="layoutIndex">Layout index.</param>
		public Note(float duration, bool isRest, int layoutIndex) {
			this.duration = duration;
			this.isRest = isRest;
			this.layoutIndex = layoutIndex;
		}
		
		/// <summary>
		/// Initializes a new instance of the <see cref="RhythmosEngine.Note"/> struct cloning another note.
		/// </summary>
		/// <param name="note">Note.</param>
		public Note(Note note) {
			this.duration = note.duration;
			this.isRest = note.isRest;
			this.layoutIndex = note.layoutIndex;
		}
		
	};
}

