//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Xml;

namespace RhythmosEditor
{
	internal static class XMLUtility {
		static public string GetPathByPlatform() {
			#if UNITY_EDITOR
			return Application.dataPath;
			#elif UNITY_ANDROID
			return Application.persistentDataPath;
			#elif UNITY_IPHONE
			return GetiPhoneDocumentsPath();
			#else
			return Application.dataPath;
			#endif
		}
		
		static public XmlNode CreateNodeByName( ref XmlDocument xmlDoc,string name, string innerText)
		{
			XmlNode node = xmlDoc.CreateElement(name);
			node.InnerText = innerText;
			return node;
		}
	}
	
}

